//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eindwerk2018.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eindwerk2018.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AdresGemeente {
            get {
                return ResourceManager.GetString("AdresGemeente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string AdresNummer {
            get {
                return ResourceManager.GetString("AdresNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string AdresPostcode {
            get {
                return ResourceManager.GetString("AdresPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string AdresStraat {
            get {
                return ResourceManager.GetString("AdresStraat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AdresTitle {
            get {
                return ResourceManager.GetString("AdresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name .
        /// </summary>
        public static string ColorNameEn {
            get {
                return ResourceManager.GetString("ColorNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Name.
        /// </summary>
        public static string ColorNameFr {
            get {
                return ResourceManager.GetString("ColorNameFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch Name .
        /// </summary>
        public static string ColorNameNl {
            get {
                return ResourceManager.GetString("ColorNameNl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorTitle {
            get {
                return ResourceManager.GetString("ColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string fiberActive {
            get {
                return ResourceManager.GetString("fiberActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Color.
        /// </summary>
        public static string fiberFiberColor {
            get {
                return ResourceManager.GetString("fiberFiberColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Number.
        /// </summary>
        public static string fiberFiberNr {
            get {
                return ResourceManager.GetString("fiberFiberNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOID.
        /// </summary>
        public static string fiberFoid {
            get {
                return ResourceManager.GetString("fiberFoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOID fiber Number.
        /// </summary>
        public static string fiberFoidFiberNr {
            get {
                return ResourceManager.GetString("fiberFoidFiberNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Id.
        /// </summary>
        public static string fiberFoidKabelId {
            get {
                return ResourceManager.GetString("fiberFoidKabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Name.
        /// </summary>
        public static string fiberFoidKabelName {
            get {
                return ResourceManager.GetString("fiberFoidKabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOID name.
        /// </summary>
        public static string fiberFoidName {
            get {
                return ResourceManager.GetString("fiberFoidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Odf Id.
        /// </summary>
        public static string fiberFoidOdfEndId {
            get {
                return ResourceManager.GetString("fiberFoidOdfEndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Odf Name.
        /// </summary>
        public static string fiberFoidOdfEndName {
            get {
                return ResourceManager.GetString("fiberFoidOdfEndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Odf Id.
        /// </summary>
        public static string fiberFoidOdfStartId {
            get {
                return ResourceManager.GetString("fiberFoidOdfStartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Odf Name.
        /// </summary>
        public static string fiberFoidOdfStartName {
            get {
                return ResourceManager.GetString("fiberFoidOdfStartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Length.
        /// </summary>
        public static string fiberFoidSectieLength {
            get {
                return ResourceManager.GetString("fiberFoidSectieLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Section Number.
        /// </summary>
        public static string fiberFoidSectieNr {
            get {
                return ResourceManager.GetString("fiberFoidSectieNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOID Serial Number.
        /// </summary>
        public static string fiberFoidSerialNr {
            get {
                return ResourceManager.GetString("fiberFoidSerialNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Sectie.
        /// </summary>
        public static string fiberFoidvirtual {
            get {
                return ResourceManager.GetString("fiberFoidvirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Color.
        /// </summary>
        public static string fiberModuleColor {
            get {
                return ResourceManager.GetString("fiberModuleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Number.
        /// </summary>
        public static string fiberModuleNr {
            get {
                return ResourceManager.GetString("fiberModuleNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Order Number.
        /// </summary>
        public static string fiberOrderNr {
            get {
                return ResourceManager.GetString("fiberOrderNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string fiberQuality {
            get {
                return ResourceManager.GetString("fiberQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string FoidComments {
            get {
                return ResourceManager.GetString("FoidComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string FoidCreationDate {
            get {
                return ResourceManager.GetString("FoidCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End ODF id.
        /// </summary>
        public static string FoidEndOdfId {
            get {
                return ResourceManager.GetString("FoidEndOdfId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibers.
        /// </summary>
        public static string FoidFibers {
            get {
                return ResourceManager.GetString("FoidFibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last status update.
        /// </summary>
        public static string FoidLastStatusDate {
            get {
                return ResourceManager.GetString("FoidLastStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string FoidLength {
            get {
                return ResourceManager.GetString("FoidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length OTDR.
        /// </summary>
        public static string FoidLengthOtdr {
            get {
                return ResourceManager.GetString("FoidLengthOtdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FoidName {
            get {
                return ResourceManager.GetString("FoidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Fibers.
        /// </summary>
        public static string FoidNrOfFibers {
            get {
                return ResourceManager.GetString("FoidNrOfFibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Id.
        /// </summary>
        public static string FoidRequestorId {
            get {
                return ResourceManager.GetString("FoidRequestorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ODF id.
        /// </summary>
        public static string FoidStartOdfId {
            get {
                return ResourceManager.GetString("FoidStartOdfId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ODF Name.
        /// </summary>
        public static string FoidStartOdfName {
            get {
                return ResourceManager.GetString("FoidStartOdfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FoidStatus {
            get {
                return ResourceManager.GetString("FoidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Date.
        /// </summary>
        public static string HistoryDate {
            get {
                return ResourceManager.GetString("HistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string HistoryId {
            get {
                return ResourceManager.GetString("HistoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string HistoryTable {
            get {
                return ResourceManager.GetString("HistoryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string HistoryUser {
            get {
                return ResourceManager.GetString("HistoryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string KabelCreationDate {
            get {
                return ResourceManager.GetString("KabelCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CableType.
        /// </summary>
        public static string KabelKabelType {
            get {
                return ResourceManager.GetString("KabelKabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string KabelName {
            get {
                return ResourceManager.GetString("KabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string KabelOwner {
            get {
                return ResourceManager.GetString("KabelOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string KabelReference {
            get {
                return ResourceManager.GetString("KabelReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable.
        /// </summary>
        public static string KabelTitle {
            get {
                return ResourceManager.GetString("KabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Type.
        /// </summary>
        public static string KabelTypeTitle {
            get {
                return ResourceManager.GetString("KabelTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string LinkAdd {
            get {
                return ResourceManager.GetString("LinkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LinkBack {
            get {
                return ResourceManager.GetString("LinkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to index.
        /// </summary>
        public static string LinkBackList {
            get {
                return ResourceManager.GetString("LinkBackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string LinkCreate {
            get {
                return ResourceManager.GetString("LinkCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string LinkCreate2 {
            get {
                return ResourceManager.GetString("LinkCreate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LinkDelete {
            get {
                return ResourceManager.GetString("LinkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string LinkDetails {
            get {
                return ResourceManager.GetString("LinkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LinkEdit {
            get {
                return ResourceManager.GetString("LinkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Fibers.
        /// </summary>
        public static string LinkEditFibers {
            get {
                return ResourceManager.GetString("LinkEditFibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sections.
        /// </summary>
        public static string LinkEditSection {
            get {
                return ResourceManager.GetString("LinkEditSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New search.
        /// </summary>
        public static string LinkNewSearch {
            get {
                return ResourceManager.GetString("LinkNewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string LinkOther {
            get {
                return ResourceManager.GetString("LinkOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LinkSave {
            get {
                return ResourceManager.GetString("LinkSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LinkSearch {
            get {
                return ResourceManager.GetString("LinkSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Options.
        /// </summary>
        public static string LinkSearchOptions {
            get {
                return ResourceManager.GetString("LinkSearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string LocationBedrijf {
            get {
                return ResourceManager.GetString("LocationBedrijf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometric point.
        /// </summary>
        public static string LocationBK {
            get {
                return ResourceManager.GetString("LocationBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS  Latidude ( 50,540135 ).
        /// </summary>
        public static string LocationGpsLat {
            get {
                return ResourceManager.GetString("LocationGpsLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Longitude  ( 3,551163 ).
        /// </summary>
        public static string LocationGpsLong {
            get {
                return ResourceManager.GetString("LocationGpsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrabel location.
        /// </summary>
        public static string LocationInfrabel {
            get {
                return ResourceManager.GetString("LocationInfrabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        public static string LocationLcode {
            get {
                return ResourceManager.GetString("LocationLcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        public static string LocationLijnNr {
            get {
                return ResourceManager.GetString("LocationLijnNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationTitle {
            get {
                return ResourceManager.GetString("LocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description French.
        /// </summary>
        public static string LocationTypeDescFr {
            get {
                return ResourceManager.GetString("LocationTypeDescFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Dutch.
        /// </summary>
        public static string LocationTypeDescNl {
            get {
                return ResourceManager.GetString("LocationTypeDescNl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Id.
        /// </summary>
        public static string LocationTypeId {
            get {
                return ResourceManager.GetString("LocationTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name French.
        /// </summary>
        public static string LocationTypeNameFR {
            get {
                return ResourceManager.GetString("LocationTypeNameFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Dutch.
        /// </summary>
        public static string LocationTypeNameNl {
            get {
                return ResourceManager.GetString("LocationTypeNameNl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type.
        /// </summary>
        public static string LocationTypeTitle {
            get {
                return ResourceManager.GetString("LocationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Id.
        /// </summary>
        public static string OdfLocationId {
            get {
                return ResourceManager.GetString("OdfLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string OdfLocationName {
            get {
                return ResourceManager.GetString("OdfLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OdfName {
            get {
                return ResourceManager.GetString("OdfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF.
        /// </summary>
        public static string OdfTitle {
            get {
                return ResourceManager.GetString("OdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string OdfTypeDescription {
            get {
                return ResourceManager.GetString("OdfTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Id.
        /// </summary>
        public static string OdfTypeId {
            get {
                return ResourceManager.GetString("OdfTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OdfTypeName {
            get {
                return ResourceManager.GetString("OdfTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF Type.
        /// </summary>
        public static string OdfTypeTitle {
            get {
                return ResourceManager.GetString("OdfTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor User name.
        /// </summary>
        public static string RequestorUserName {
            get {
                return ResourceManager.GetString("RequestorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string SectieActive {
            get {
                return ResourceManager.GetString("SectieActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Fibers.
        /// </summary>
        public static string SectieFibers {
            get {
                return ResourceManager.GetString("SectieFibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Id.
        /// </summary>
        public static string SectieKabelId {
            get {
                return ResourceManager.GetString("SectieKabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Name.
        /// </summary>
        public static string SectieKabelName {
            get {
                return ResourceManager.GetString("SectieKabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string SectieLength {
            get {
                return ResourceManager.GetString("SectieLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectie Number.
        /// </summary>
        public static string SectieNr {
            get {
                return ResourceManager.GetString("SectieNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odf End Id.
        /// </summary>
        public static string SectieOdfEndId {
            get {
                return ResourceManager.GetString("SectieOdfEndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF End Name.
        /// </summary>
        public static string SectieOdfEndName {
            get {
                return ResourceManager.GetString("SectieOdfEndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odf Start Id.
        /// </summary>
        public static string SectieOdfStartId {
            get {
                return ResourceManager.GetString("SectieOdfStartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF Start Name.
        /// </summary>
        public static string SectieOdfStartName {
            get {
                return ResourceManager.GetString("SectieOdfStartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string SectieTitle {
            get {
                return ResourceManager.GetString("SectieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SectieTypeDescription {
            get {
                return ResourceManager.GetString("SectieTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Id.
        /// </summary>
        public static string SectieTypeId {
            get {
                return ResourceManager.GetString("SectieTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string SectieTypeName {
            get {
                return ResourceManager.GetString("SectieTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Type.
        /// </summary>
        public static string SectieTypeTitle {
            get {
                return ResourceManager.GetString("SectieTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        public static string SectieTypeVirtual {
            get {
                return ResourceManager.GetString("SectieTypeVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Section.
        /// </summary>
        public static string Sectievirtual {
            get {
                return ResourceManager.GetString("Sectievirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string StatusAccept {
            get {
                return ResourceManager.GetString("StatusAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Service.
        /// </summary>
        public static string StatusInService {
            get {
                return ResourceManager.GetString("StatusInService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string StatusNew {
            get {
                return ResourceManager.GetString("StatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string StatusRemoved {
            get {
                return ResourceManager.GetString("StatusRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string StatusReserved {
            get {
                return ResourceManager.GetString("StatusReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserUserName {
            get {
                return ResourceManager.GetString("UserUserName", resourceCulture);
            }
        }
    }
}
